// <auto-generated />
namespace WhatDo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitializingLatestDatabaseVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitializingLatestDatabaseVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "201801291717230_InitializingLatestDatabaseVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
